### ISSUE TITLE
StreamLambdaTracing does not extract context from request 

### ISSUE THREAD

**Issue by chet20r** [newrelic/java-aws-lambda#44]
Looking at the `StreamLambdaTracing` implementation, it looks like the `extractContext` method just returns `null` and ignores the existing newrelic distributed tracing headers already present in the incoming request. Due to this, the existing Spans in the requests are ignored which doesn't really help in Distributed tracing.

```java
public void instrumentRequest(InputStream input, OutputStream output, Context context, RequestStreamHandler realHandler) throws IOException {
        Tracer tracer = GlobalTracer.get();
        SpanContext spanContext = this.extractContext(tracer, input);

```

```java
 protected SpanContext extractContext(Tracer tracer, InputStream input) {
        return null;
    }
```

**Comment by MattWhelan** [comment]
Since we have no type information to guide us in how to interpret the invocation, we can't extract context automatically. Instead, this method is provided as a stub to be overridden in specialized versions of StreamLambdaTracing. 

For (rather limited) automatic trace propagation, LambdaTracing is a better choice. Realistically though, you're likely to need to create a custom subclass to handle your invocation event type in that case as well, unless your invocation event is an API Gateway Proxy event represented as a Map.

**Comment by patrickjamesbarry** [comment]
It would be great if this class (StreamLambdaTracing) was mentioned in the README and its limitations, along with an example implementation of what you are suggesting.
